### ISSUE TITLE
Register for bower

### ISSUE THREAD

**Issue by thelfensdrfer** [creativetimofficial/light-bootstrap-dashboard#1]
It would be great if you could make the dashboard available on bower.

**Comment by alexandru-paduraru** [comment]
Hi, at this moment we don't have a developer in our team who has experience with bower, if you could guide us on how we can integrate it that would be great. Or why not, if you have experience using bower can you please implement that part and create a pull request? So the other users will have access to it.

Keep in touch,
Alex

**Comment by thelfensdrfer** [comment]
I am not saying that i am experienced with bower but i yesterday successfully published a package so I will try.

**Comment by abr4xas** [comment]
@thelfensdrfer can you explain more about "make the dash available on bower"? You mean, create a package with all styles?

**Comment by thelfensdrfer** [comment]
Yeah, like [AdminLTE](https://github.com/almasaeed2010/AdminLTE) for example.

**Comment by abr4xas** [comment]
@thelfensdrfer you need some help with that? :smiley:

**Comment by thelfensdrfer** [comment]
No, I will create a pr today. Just wanted to make sure you are ok with that;)

**Comment by abr4xas** [comment]
No problem with that!! :smile:

**Comment by abr4xas** [comment]
@thelfensdrfer https://github.com/abr4xas/7-stroke :smile:

**Comment by thelfensdrfer** [comment]
Ahh sry I thought you were the one from creativetim I first talked to, had to sound strange;) And he already said that I could create a pr...Kinda messed up here :/

**Comment by abr4xas** [comment]
ROLF!! no problem dude... Like @alexandru-paduraru said, you could create that pr...

**Comment by thelfensdrfer** [comment]
I think i am too old...already created that pr half a year ago. But no news on that https://github.com/timcreative/light-bootstrap-dashboard/pull/2
