### ISSUE TITLE
Modal 

### ISSUE THREAD

**Issue by iunary** [creativetimofficial/light-bootstrap-dashboard#14]
There is an issue with boostrap modal check out the following image

![modal](https://cloud.githubusercontent.com/assets/1395589/20223788/17249322-a833-11e6-9b7f-a22141a82492.png)

Any hint how to fix it?

**Comment by alexandru-paduraru** [comment]
@iunary thank you for using our product. You have 2 options: 1. move the body of the modal outside of the div.wrapper or 2. add this code: $('.modal').appendTo("body"); inside assets/js/light-bootstrap-dashboard.js inside $(document).ready(function(){... function. Please let us know if that was working fine. 

Best, Alex!

**Comment by iunary** [comment]
@alexandru-paduraru It worked, thank very much.

**Comment by irsyadadl** [comment]
It doesn't work at all. Even I follow both of step.

**Comment by alexandru-paduraru** [comment]
@irsyadadl do you have an example link so we can check?

**Comment by karlitu** [comment]
The second option worked for me. Thanks!

**Comment by ulfahfaridah** [comment]
The first option worked for me. Thanks!

**Comment by Msingh91** [comment]
The first option works but distorts the entire dashboard. I tried the second option but it did not work for me. Regarding the second option, is there anything I am doing wrong?

**Comment by Msingh91** [comment]
I am wanting to include the modal inside of div.wrapper. When i use the code: $('.modal').appendTo("body"); 
I am still getting the same issue @iunary was having. Is there any other way to fix this without moving the modal outside of the div?

**Comment by VoTuanNguyen** [comment]
I have resolved it by remove "z-index:2" in class "main-panel".

**Comment by idhanze** [comment]
it is not working for me

**Comment by idhanze** [comment]
my modal showing on inspector, but not on the page
