### ISSUE TITLE
checkbox with ng-repeat not working

### ISSUE THREAD

**Issue by andreadompe** [creativetimofficial/light-bootstrap-dashboard#15]
I've tried              
              <li ng-repeat="therapy in therapies">
                <label class="checkbox">{{therapy.name}}
                  <input type="checkbox" id="ck_{{therapy.suffix}}" value="{{therapy}}"data-toggle="checkbox">
                </label>
              </li>

The result is 
![checkbox1](https://cloud.githubusercontent.com/assets/11677749/21160206/3c85768a-c184-11e6-80d2-723f7da321a1.png)

Only if i select the label i can see the checkbox
![checkbox2](https://cloud.githubusercontent.com/assets/11677749/21160302/b0a68554-c184-11e6-859e-b4206645d9f3.png)

How can i do for fixing it?

Thanks in advance

**Comment by alexandru-paduraru** [comment]
@andreadompe thank you for using our product. We are working on a native Angular2 version of LBD which can be found Here:https://github.com/creativetimofficial/light-bootstrap-dashboard-angular

Please check how we integrated checkboxes and the libraries and let us know if you have any other feedback that we can use to improve that version.

All the best,
Alex

**Comment by andreadompe** [comment]
@alexandru-paduraru Thankyou for your attention.
I've just check the angular version of your amazing admin at https://github.com/creativetimofficial/light-bootstrap-dashboard-angular, but the problem appears only when i use the ng-repeat, in your version there  isn't the ng-repeat in the dashboard.

Best regards

Andrea

**Comment by alexandru-paduraru** [comment]
@andreadompe got it, we will check it with ng-repeat when we will get back to the office on Monday, can you please send us the full code that you used? We will add it in our product and see how we can work with that.

Best,
Alex

**Comment by andreadompe** [comment]
Hi @chelaruc,
thanks so much! I've found the way!
