### ISSUE TITLE
Mobile menu on left side & swipe to open

### ISSUE THREAD

**Issue by fullhdpixel** [creativetimofficial/light-bootstrap-dashboard#17]
This dashboard is awesome! In particular the menu is really well designed.

Though I have two questions:

1. How do I put the mobile menu on the left side of the screen instead of the right?
2. Can you point me to a library that will enable swipe to open on this menu?

I want to recreate the android experience with this dashboard

**Comment by meworking** [comment]
I would like to know the answer to this as well!

**Comment by fullhdpixel** [comment]
@meworking check out slideout.js.org
