### ISSUE TITLE
checkbox can not display the box when create with js code 

### ISSUE THREAD

**Issue by zj2050** [creativetimofficial/light-bootstrap-dashboard#18]
@alexandru-paduraru 
when i add checkbox in js code like :
`
                var t6 = $(  '                  <tbody>' +
                              
                              
                              '                  </tbody> ' 
                            )

                for (var c = 0 ; c < rowdata.length ; c++)
                {
                    var tr = $('<tr>  </tr>');

                    var tck = $('<td> <label class="checkbox">' +
                                '<input type="checkbox" value="" id="' + rowdata[c].xh + ' data-toggle="checkbox" checked="false">' +
                                '</label> </td>'
                                );
                    //tck.bind()
                    tr.append(tck);

                    var tdesc = $('<td>' + rowdata[c].title + '</td>');
                    tr.append(tdesc);

                    var thint = $('<td class="td-actions text-right">' +
                                    '<button type="button" rel="tooltip" id="hi_' + rowdata[c].xh + '" title="" class="btn btn-info  btn-simple btn-lg">' +
                                    '<i class="fa fa-edit"></i>' +
                                    '</button> </td>'
                                );
                    tr.append(thint);

                    t6.append(tr);
                }

`

will not display box, but if click at box position ,it will show ???

![error](https://cloud.githubusercontent.com/assets/4464947/24939498/5b9c80dc-1f70-11e7-90c0-9fd9f90a1438.jpg)

the first one show box ,because i have clicked it , next two not show ,but if click it when will show ,why ? and how to solute it ?

thanks

**Comment by alexandru-paduraru** [comment]
@zj2050 thank you for using our product. You need to call the method that is activating the checkboxes after all the dynamically added checkboxes are inserted in the page like this:


 ```
$('[data-toggle="checkbox"]').each(function () {
     var $checkbox = $(this);
     $checkbox.checkbox();
});
````

Best,
Alex

**Comment by zj2050** [comment]
@alexandru-paduraru 
it's great !
thx

**Comment by zj2050** [comment]
@alexandru-paduraru 
hi alex, another thing, how to set checked by js 
`
xinfeiradio.checked = true;`
above code not work

Best

**Comment by zj2050** [comment]
$('[data-toggle="checkbox"]').each(function () {
    var $checkbox = $(this);
    if( $checkbox.value == 1)
    {
       $checkbox.checked = true;
    }
});

**Comment by alexandru-paduraru** [comment]
@zj2050 please check in the documentation of GSDK under the checkboxes examples: http://demos.creative-tim.com/get-shit-done/components.html how to check/uncheck/toggle them. Hope this will help you :D

**Comment by jmliz** [comment]
@zj2050 I had this same issue when working with AngularJS when loading dynamically a view with dynamic checkboxes on its own. I didn't had to call .checkbox() (it will show 'not a function' error for some reason, I'm no jquery master :P).

I solved the problem when I linked to the jquery version the gsd plugin come with (I was using another version) and not calling the .checkbox() function but adding manually the icons inside the .checkbox label:

```
<label class="checkbox" id="{{cat}}" data-ng-repeat="cat in cats">
          <span class="icons">
                  <span class="first-icon fa fa-square-o"></span>
                   <span class="second-icon fa fa-check-square-o"></span>
           </span>
            <input type="checkbox" value="{{cat}}" data-toggle="checkbox">
            {{cat}}
</label>
```

I don't know if it's the best solution @alexandru-paduraru, but hopefully this helps someone else :P

**Comment by alexandru-paduraru** [comment]
@jmliz we have a solution for checkboxes/radios made only with CSS, without any jQuery library, please check it here: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/issues/32

We will do this update in the next 1-2 weeks.

Hope this helps.

Best,
Alex
