### ISSUE TITLE
Scrolling with arrow keys not working

### ISSUE THREAD

**Issue by eichf** [creativetimofficial/light-bootstrap-dashboard#25]
This is true also for the live preview. When opening the page (any page of the dashboard) in Firefox ESR 52.2.1 64bit, scrolling has to be done using a mouse; arrow keys are not working.

Have not tried other browsers as changing browsers is not viable for me.

There are several `event.preventDefault()` calls in `assets/js/jquery-1.10.2.js` and `assets/js/bootstrap.min.js` which apparently can be used to do this. I am, however, not a JS or web developeri just found [this stackoverflow thread](https://stackoverflow.com/questions/8916620/disable-arrow-key-scrolling-in-users-browser). Why the method described there would be relevant here I don't really see, but it's all I could find on this behaviour in a couple of minutes of Google search, before I decided to look at your live example and noticed it has the same bug.

**Comment by floGik** [comment]
@alexandru-paduraru thanks for the reply. I'm probably not going to be fiddling with the code any longer as I'm using Light Bootstrap Dashboard for a uni project I'm close to finishing, but I do really like your stuff and will certainly use again/recommend.

Just a quick note: The arrow keys _do work_ in the Paper Dashboard, but only after focusing the content frame with the mouse.
