### ISSUE TITLE
Bootstrap 4 beta

### ISSUE THREAD

**Issue by JhumanJ** [creativetimofficial/light-bootstrap-dashboard#26]
Hi there!
Have you planned to release a bootstrap 4(beta) compatible version? Thanks!

**Comment by alexandru-paduraru** [comment]
@JhumanJ thank you for your interest in our product. Yes, we are working on the Bootstrap 4 version and also for a converter which will take the BS3 code and migrate it to BS4 code. So no worries if you've worked with BS3. We will have something in a couple of weeks.

Best,
Alex

**Comment by Omnia-Code** [comment]
Any idea when the BS4 version is ready?

**Comment by alexandru-paduraru** [comment]
@Omnia-Code we have a WIP version here: https://github.com/creativetimofficial/light-bootstrap-dashboard/tree/bs4-dev Please check it and let us know if everything is fine.

Best,
Alex
