### ISSUE TITLE
Table responsive not working

### ISSUE THREAD

**Issue by fahruddin14431** [creativetimofficial/light-bootstrap-dashboard#27]
i have many field in my table and table resposive not work correctly

**Comment by groovemen** [comment]
Hello @fahruddin14431, 

Thank you for using our products, please set the following properties for the `table-responsive` class: 
   ```
.table-resonsive { 
   width: 100%;
    margin-bottom: 15px;
    overflow-x: scroll;
    overflow-y: hidden;
    -ms-overflow-style: -ms-autohiding-scrollbar;
    -webkit-overflow-scrolling: touch;
}
```

Best, 
Stefan
