### ISSUE TITLE
the class input-group-addon issue

### ISSUE THREAD

**Issue by benjieperez** [creativetimofficial/light-bootstrap-dashboard#29]
![screenshot-2017-11-26 light bootstrap dashboard pro by creative tim](https://user-images.githubusercontent.com/20369043/33238856-00d77340-d2d1-11e7-90c0-f364f1276af7.png)
when im using that class in a input with required="required" the style of span using that class input-group-addon will also override the css how should i do it?

**Comment by dragosct10** [comment]
Hi, @benjieperez! Thank you for using our product. In the free version, we don't use the input groups, but we have already done the input groups in the [PRO version](http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/forms/regular.html). Regards,
Dragos

**Comment by benjieperez** [comment]
btw its fix now, i had the pro version now
