### ISSUE TITLE
Modals are off screen when text is too long

### ISSUE THREAD

**Issue by daniel-dia** [creativetimofficial/light-bootstrap-dashboard#30]
When a modal with a big text appears, then it goes off the screen (to the bottom os screen)
I fixed it by removing the fallowing rules from my CSS

```
.modal.show .modal-dialog {
    -webkit-transform: translate(0, 30%);
    -o-transform: translate(0, 30%);
    transform: translate(0, 30%);
}
```

**Comment by groovemen** [comment]
Hi Artsjedi,

Thank you for using our product and appreciate for solving the issue.
You can also erase the `modal-mini` class from the main modal div, and set a lesser value to `transform: translate:(...)`.

Regards, 
Stefan
