### ISSUE TITLE
date time picker in light bootstrap v3

### ISSUE THREAD

**Issue by benjieperez** [creativetimofficial/light-bootstrap-dashboard#31]
why is it datetimepicker not working in mobile? like what it is in the pro version demo?
see their demo
https://demos.creative-tim.com/bs3/light-bootstrap-dashboard-pro/examples/forms/extended.html
when i try to view the website in mobile to be responsive datetimepicker doesnt show up
Please fix this bug asap

**Comment by groovemen** [comment]
Hello @benjieperez,

Thank you for using our products, I double checked the datetimepicker and it works just fine. Please provide us a link to your project to make a quick check. 

Best, 
Stefan
