### ISSUE TITLE
Demo documentation has a broken link to an 'elements page'.

### ISSUE THREAD

**Issue by gkopff** [creativetimofficial/light-bootstrap-dashboard#32]
The documentation [here](http://demos.creative-tim.com/light-bootstrap-dashboard/documentation/tutorial-components.html) has the following text in the 'New Components' section:

> For more details regarding the components, go to our `elements page`.

The link points to: http://demos.creative-tim.com/light-bootstrap-dashboard/documentation/elements.html

However, this page doesn't exist.

**Comment by naren67074** [comment]
hi

**Comment by groovemen** [comment]
Hello @gkopff, 

Thank you for using our products and for letting us know about this issue, we'll fix it in the next update. The link should be: https://demos.creative-tim.com/light-bootstrap-dashboard/examples/dashboard.html 

Best, 
Stefan
