### ISSUE TITLE
Problem with WYSIWYG

### ISSUE THREAD

**Issue by calypso333** [creativetimofficial/light-bootstrap-dashboard#33]
I managed to make most of it work with the template (I'm using Laravel), but:
when a user tries to edit or add a new link using WYSIWYG the whole page turns dark and disabled.
I tried to solve this by myself but I can't find the file that deals with the box.

Thank you
![pro](https://user-images.githubusercontent.com/36621354/36369927-c15d118e-1565-11e8-8d45-85c3e61d00a6.JPG)

**Comment by dragosct10** [comment]
Hi, @calypso333! Thank you for using our product. Please, can you tell me if you use the latest version of the dashboard? Regards, Dragos

**Comment by calypso333** [comment]
I think it is, in the version I got it says 2017.

**Comment by dragosct10** [comment]
Hi, @calypso333! Sorry for the late response. Please, can you give me the link of your project to check what is the problem? Regards, Dragos
