### ISSUE TITLE
scroll bar on the bottom is shown out in IE 11

### ISSUE THREAD

**Issue by rrongcheng** [creativetimofficial/light-bootstrap-dashboard#34]
When I access http://demos.creative-tim.com/light-bootstrap-dashboard/examples/notifications.html via my IE 11, the bottom scroll bar shown.
The 'log out' button on the top menu is out of the line.
![image](https://user-images.githubusercontent.com/15684748/36522744-47a6f4d8-17d9-11e8-94ac-03cb3db3e839.png)

**Comment by groovemen** [comment]
Hello @rrongcheng, thank you for using our product;
please visit the following link: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/issues/49, I opened a new issue with this problem. 
Hope this information helps you.

Greetings, Stefan
